member email invite
go-saas/go-saas-ui pull request #17
Opened 2020-09-10 16:24 UTC by loeffelr

2020-09-10 17:15 UTC, loeffelr commented
http://emailregex.com/

2020-09-10 17:16 UTC, loeffel-io requested changes

2020-09-10 17:16 UTC, loeffel-io commented on src/components/modals/settings/team/Create.vue
> +    if (this.teamCreate.emails?.length === 0) {
kein `?` verwenden, so machen wie bei allen anderen auch - checken ob emails `null` ist

2020-09-10 17:16 UTC, loeffel-io commented on src/components/modals/settings/team/Create.vue
> +      if (EmailValidatorUtil.isValidEmail(this.teamCreate.emails![i].email!)) {
Kannst du einfach eine ValidatorUtil anlegen 
Bei Go saas muss so wenig wie möglich rein (bei finsmart sind wir da flexibler)

2020-09-10 17:16 UTC, loeffel-io commented on src/components/modals/settings/team/Create.vue
> +        isAllEmailsValid = true;
das ist inperformant und kannst einfach ein return nehmen sobald es eine falsche email gibt

2020-09-10 17:16 UTC, loeffel-io commented on src/utils/emailValidator.ts
> +    return emailRegExp.test(email);
regex hier unten rein bitte 
sonst fängt man an zu suchen, dafür brauchen wir keine extra var

2020-09-10 17:16 UTC, loeffel-io commented on src/components/modals/settings/team/Create.vue
> +    console.log(this.teamCreate);
console log?

2020-09-10 17:17 UTC, loeffelr commented on src/components/modals/settings/team/Create.vue
> +    if (this.teamCreate.emails?.length === 0) {
email ist aber nicht null, sondern []

2020-09-10 17:18 UTC, loeffel-io commented
Habe hier noch etwas drüber nachgedacht, wir müssen ein neues Struct TeamEmails machen statt TeamCreate in einem neuen File, damit wir beim Invite das nutzen können und im team create 
Also einfach in ein extra File packen

2020-09-10 17:27 UTC, loeffel-io commented on src/components/modals/settings/team/Create.vue
> +    if (this.teamCreate.emails?.length === 0) {
`emails: TeamCreateEmail[] | null = [];` 

sie kann aber null sein

2020-09-10 17:42 UTC, loeffel-io commented on src/utils/validator.ts
> +    return emailRegExp.test(email);
`test` hab ich noch nie gesehen, heißt das nicht match?

2020-09-10 17:43 UTC, loeffel-io commented on src/utils/validator.ts
> +    return emailRegExp.test(email);
test kann man anscheint auch verwenden und gibt einfach bool zurück, statt wie bei match die matches 
das passt 👍

2020-09-10 18:22 UTC, loeffel-io requested changes

2020-09-10 18:22 UTC, loeffel-io commented on src/components/modals/settings/team/Create.vue
> +            <b-form-group :label="$saas.t('pages.team.forms.create.fields.invite.label')" label-for="team-invitation">
oben heißt es invite unten email, das kneift auch noch

2020-09-10 18:22 UTC, loeffel-io commented on src/structs/team-create.ts
> +  emails: TeamInvitation[] | null = [];
das sind jetzt keine `emails` mehr 
invitations wäre gut denke ich

2020-09-13 08:46 UTC, loeffel-io requested changes

2020-09-13 08:46 UTC, loeffel-io commented on src/messages/pages/settings/team.json
> +          "email": "All emails have to be valid"
lass da mal noch ein parent machen "invations" und dann emails darunter packen :-* Sonst sieht alles super aus!

2020-09-14 10:01 UTC, loeffel-io requested changes

2020-09-14 10:01 UTC, loeffel-io commented on src/components/modals/settings/team/Create.vue
> +                    {{ $saas.t('pages.team.forms.create.validations.email') }}
diggaaaaaaaa

2020-09-14 13:50 UTC, merged